-- Seed file for local development
-- This file runs automatically after migrations during `supabase db reset`

-- ============================================================================
-- IMPORTANT: Creating Test Users
-- ============================================================================
-- You CANNOT insert directly into auth.users from SQL.
-- Instead, create test users via:
--   1. Local Studio UI: http://localhost:54323 → Authentication → Users
--   2. Auth API signup endpoint (see curl example below)
--   3. Your app's signup page
--
-- Once you have test users, note their UUIDs and use them below.
-- ============================================================================

-- Example curl command to create a test user (run in terminal):
-- curl -X POST 'http://localhost:54321/auth/v1/signup' \
--   -H "apikey: YOUR_LOCAL_ANON_KEY" \
--   -H "Content-Type: application/json" \
--   -d '{
--     "email": "test@example.com",
--     "password": "password123",
--     "options": {
--       "data": {
--         "display_name": "Test User"
--       }
--     }
--   }'

-- ============================================================================
-- Test Data with Real User UUID
-- ============================================================================
-- 
-- ⚠️  IMPORTANT: This seed data requires a user to exist first!
-- ⚠️  Running `supabase db reset` wipes auth.users, so use the helper script:
-- 
--     ./scripts/reset-with-seed.sh
-- 
-- This script will:
--   1. Reset the database
--   2. Create a test user via Auth API
--   3. Insert seed data with the actual user ID
-- 
-- Alternatively, create a user manually and update the UUID below.
-- ============================================================================

-- Note: Commented out because auth user must exist first
-- Use scripts/reset-with-seed.sh instead

-- DO $$
-- DECLARE
--   test_user_id UUID := '6229270e-4abd-429c-94f7-faa9d4ed47ba';
--   morning_room_id UUID;
--   night_room_id UUID;
-- BEGIN
--   -- Create test rooms
--   INSERT INTO rooms (name, description, created_by)
--   VALUES ('Morning Grinders', 'Early bird study group', test_user_id)
--   RETURNING id INTO morning_room_id;
-- 
--   INSERT INTO rooms (name, description, created_by)
--   VALUES ('Night Owls', 'Late night coding sessions', test_user_id)
--   RETURNING id INTO night_room_id;
-- 
--   -- Add room memberships
--   INSERT INTO room_memberships (room_id, user_id, role)
--   VALUES 
--     (morning_room_id, test_user_id, 'owner'),
--     (night_room_id, test_user_id, 'owner');
-- 
--   -- Create a sample session
--   INSERT INTO sessions (user_id, room_id, started_at, ended_at, duration_seconds)
--   VALUES (
--     test_user_id,
--     morning_room_id,
--     NOW() - INTERVAL '2 hours',
--     NOW() - INTERVAL '30 minutes',
--     5400  -- 90 minutes
--   );
-- 
--   RAISE NOTICE 'Seed data created successfully for user %', test_user_id;
-- END $$;

-- ============================================================================
-- Development Tips
-- ============================================================================
-- 1. Create users first via Studio UI or signup endpoint
-- 2. Copy their UUIDs
-- 3. Uncomment the examples above and replace UUIDs
-- 4. Run: supabase db reset
-- 5. Your test data will be ready!

